### ISSUE TITLE
Publish kondo-ui

### ISSUE THREAD

**Issue by TimDiekmann** [tbillington/kondo#22]
Kondo-ui doesn't seem to be published yet. At least `cargo install kondo-ui` fails. I can't find a way starting `kondo-ui` without downloading the binary directly or building it myself. Could you publish `kondo-ui` to crates.io so installing via cargo is straight forward?

**Comment by tbillington** [comment]
Hey @TimDiekmann , I'm with you on this one!

I'd love to publish it, unfortunately I'm relying on commits to [druid](https://github.com/xi-editor/druid/) that haven't been part of a release yet, so crates.io won't let me publish because it requires a publicly available version (a git hash is not good enough).

I'm following along closely and will release when the next version is released ! https://github.com/xi-editor/druid/issues/434

I'll leave this issue open as a reminder 😀

**Comment by tbillington** [comment]
In the meantime, you can `git clone` then `cargo install --path` as an alternative!

**Comment by tbillington** [comment]
Hey @TimDiekmann , just letting you know `kondo-ui` is now published on crates.io. As I mentioned you'll still need to satisfy druids requirements, which are cairo on mac and gtk3 on linux.

Let me know if there's anything else 🙂

**Comment by TimDiekmann** [comment]
Thanks you for notifying!
