### ISSUE TITLE
Add progress indicator

### ISSUE THREAD

**Issue by puzzlewolf** [tbillington/kondo#28]
Hi, thanks for this project! 
It has been really useful for me, by showing me exactly *how* large those Rust target folders become :)

One nitpick: When I ran `kondo` on my home directory, it took a very long time. That's ok, you're working on parallelization :+1:. However, I'd have appreciated some kind of output to show me the process hasn't crashed :) Maybe add a `--verbose` flag and output the name folder that's currently being analyzed?

**Comment by tbillington** [comment]
Glad it was useful!

I've actually made some changes on master for the CLI version, which includes outputting as it goes rather than all at once at the end. You can install from cargo with `cargo install kondo --git https://github.com/tbillington/kondo/`.

Would you be able to try running the latest version and let me know if it is more helpful?

**Comment by tbillington** [comment]
It also contains the `clean` subcommand. You can get info via `kondo --help`.

**Comment by tbillington** [comment]
Actually you'll need to run `kondo clean --dry-run` to see what I'm talking about, apologies.

**Comment by tbillington** [comment]
Since this issue was opened kondo has become much faster and more responsive. If you still feel the need for progress in the CLI please reply :)
