### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by qm3ster** [tbillington/kondo#30]
Would deleting things that fall under explicit `.gitignore` globs (as opposed to plain untracked files, which is wildly dangerous) be a useful thing for most people?

**Comment by tbillington** [comment]
Hmm, I like the idea, but it's risky, and quite specific. I'd rather have new project types/directories added as a first class option in Kondo than assuming ignored things can be deleted.

I can guarantee `target` in a rust project can be remade from scratch, but someone's other project might have some kind of "data" folder that isn't synced to git because it's non-source code/binary files, but it's still important data.

**Comment by qm3ster** [comment]
![image](https://user-images.githubusercontent.com/10551234/193566378-770c00d2-113b-4760-b2c7-08dc268b3e2d.png)
suspicious
